/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create rate quote */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RateRequest"];
                };
            };
            responses: {
                /** @description Rate results including partial carrier failures */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/routing/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get recommendation for an existing quote */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoutingRequest"];
                };
            };
            responses: {
                /** @description Recommendation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm human or automatic decision */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DecisionRequest"];
                };
            };
            responses: {
                /** @description Decision snapshot created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DecisionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shipments */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    carrier_id?: string;
                    q?: string;
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Shipment list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create shipment from selected offer/decision */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateShipmentRequest"];
                };
            };
            responses: {
                /** @description Shipment created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shipment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments/{shipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shipment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shipment_id: components["parameters"]["ShipmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Shipment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shipment"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shipments/{shipment_id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get normalized tracking timeline */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shipment_id: components["parameters"]["ShipmentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tracking */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrackingEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List connected carriers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Carriers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carrier score analytics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Carrier analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{carrier_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inbound carrier webhook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    carrier_code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Money: {
            /** @description Minor currency units; never float. */
            amount_minor: number;
            currency: string;
        };
        Address: {
            country: string;
            region?: string;
            city: string;
            postal_code?: string;
            address_line: string;
        };
        Package: {
            weight_grams: number;
            length_mm?: number;
            width_mm?: number;
            height_mm?: number;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            access_token: string;
            refresh_token?: string;
            expires_in: number;
        };
        RateRequest: {
            origin: components["schemas"]["Address"];
            destination: components["schemas"]["Address"];
            /** Format: date-time */
            ship_at?: string;
            /** Format: date-time */
            deadline?: string | null;
            packages: components["schemas"]["Package"][];
            cargo_value: components["schemas"]["Money"];
            cargo_type?: string;
            additional_services?: string[];
            carrier_whitelist?: string[];
            carrier_blacklist?: string[];
            /** @enum {string} */
            strategy: "optimal" | "cheapest" | "fastest" | "reliable";
        };
        CostComponent: {
            /** @enum {string} */
            type: "base" | "insurance" | "pickup" | "door_delivery" | "packaging" | "remote_area" | "pallet" | "waiting" | "declared_value" | "other";
            money: components["schemas"]["Money"];
            rate_percent?: number | null;
            description?: string;
        };
        RateOffer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            carrier_id: string;
            carrier_name?: string;
            service_code: string;
            service_name?: string;
            /** @enum {string} */
            source: "client_contract" | "logistics_os";
            cost_components?: components["schemas"]["CostComponent"][];
            total_cost: components["schemas"]["Money"];
            /** Format: date-time */
            eta?: string | null;
            deadline_margin_seconds?: number | null;
            lateness_seconds?: number | null;
            on_time_probability?: number | null;
            /** @enum {string|null} */
            probability_label?: "low" | "medium" | "high" | null;
            carrier_score?: number | null;
            /** @enum {string|null} */
            risk?: "low" | "medium" | "high" | null;
            /** @enum {string|null} */
            confidence?: "low" | "medium" | "high" | null;
            eligible: boolean;
            ineligibility_reason?: string | null;
            /** Format: date-time */
            valid_until?: string | null;
        };
        CarrierFailure: {
            /** Format: uuid */
            carrier_id?: string;
            code?: string;
            message?: string;
            retryable?: boolean;
        };
        RateResponse: {
            /** Format: uuid */
            quote_id: string;
            offers: components["schemas"]["RateOffer"][];
            failures: components["schemas"]["CarrierFailure"][];
            no_deadline_match: boolean;
            /** Format: date-time */
            valid_until?: string;
        };
        RoutingRequest: {
            /** Format: uuid */
            quote_id: string;
            /** @enum {string} */
            strategy: "optimal" | "cheapest" | "fastest" | "reliable";
        };
        Recommendation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quote_id: string;
            strategy: string;
            /** Format: uuid */
            recommended_offer_id: string;
            explanation?: string[];
            algorithm_version: string;
            policy_version?: string;
            alternatives_delta?: {
                [key: string]: unknown;
            };
        };
        DecisionRequest: {
            /** Format: uuid */
            recommendation_id: string;
            /** Format: uuid */
            selected_offer_id: string;
            /** @default false */
            override: boolean;
            override_reason?: string | null;
            override_comment?: string | null;
            /** @enum {string} */
            mode?: "manual" | "auto";
        };
        DecisionResponse: {
            /** Format: uuid */
            decision_id: string;
            /** Format: uuid */
            snapshot_id: string;
            /** Format: date-time */
            created_at?: string;
        };
        CreateShipmentRequest: {
            /** Format: uuid */
            decision_id: string;
            external_id?: string;
        };
        Shipment: {
            /** Format: uuid */
            id: string;
            external_id?: string;
            /** Format: uuid */
            decision_id?: string;
            /** Format: uuid */
            carrier_id?: string;
            tracking_number?: string;
            /** @enum {string} */
            status: "Draft" | "Quoted" | "Created" | "PickedUp" | "InTransit" | "OutForDelivery" | "Delivered" | "Exception" | "Delayed" | "Cancelled";
            /** Format: date-time */
            eta?: string | null;
            /** Format: date-time */
            deadline?: string | null;
            quoted_total_cost?: components["schemas"]["Money"];
            actual_total_cost?: components["schemas"]["Money"] | null;
        };
        TrackingEvent: {
            /** Format: date-time */
            occurred_at: string;
            normalized_status: string;
            carrier_status?: string;
            location?: string;
            description?: string;
        };
    };
    responses: never;
    parameters: {
        IdempotencyKey: string;
        ShipmentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
